name: Bug report
description: File a bug against the `uuid` project
labels: ['bug']
title: '[BUG] <title>'

body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT**: Failure to provide a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/minimal-reproducible-example) example will result in this issue being closed without further review.

  - type: textarea
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    attributes:
      label: Recipe for reproducing
      description: You saw the "IMPORTANT" note above, right?
      render: bash
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: 'Output of `npx envinfo --system --browsers --npmPackages --binaries` goes here:'
    validations:
      required: false
